---
title: "Trending_Videos_On_Youtube"
author: "Bill_Wu"
date: "03/10/2022"
output: pdf_document
---


```{r include=FALSE}

library(tidyverse)
library(ggplot2)
library(utils)
```



```{r include=FALSE}

youtube_data <- read_csv("data/Trending_videos_on_youtube_dataset.csv")

```


```{r echo=FALSE}

top10video <- youtube_data %>% 
  arrange(desc(viewCount)) %>%
  head(10)

ggplot(data = top10video, aes(x = reorder(videoTitle, viewCount), y = viewCount)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  ggtitle("Top 10 Most Viewed Videos") +
  ylab("Views") +
  xlab("Video Title")


```

```{r echo=FALSE}

youtube_data1 <- group_by(youtube_data, channelTitle)

top10channel <- summarise(youtube_data1, TotalViews = sum(viewCount)) %>%
    arrange(desc(TotalViews)) %>%
    head(10)

ggplot(data = top10channel, aes(x = reorder(channelTitle, TotalViews), y = TotalViews)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  ggtitle("Top 10 Most Viewed Channel") +
  ylab("Views") +
  xlab("Channel")


```


```{r echo=FALSE}


top10likechannel <- summarise(youtube_data1, TotalLike = sum(likeCount)) %>%
    arrange(desc(TotalLike)) %>%
    head(10)

ggplot(data = top10likechannel, aes(x = reorder(channelTitle, TotalLike), y = TotalLike)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  ggtitle("Top 10 Most Liked Channel") +
  ylab("Likes") +
  xlab("Channel")


```


```{r echo=FALSE}


top10commentchannel <- summarise(youtube_data1, TotalComment = sum(commentCount)) %>%
    arrange(desc(TotalComment)) %>%
    head(10)

ggplot(data = top10commentchannel, aes(x = reorder(channelTitle, TotalComment), y = TotalComment)) +
  geom_bar(stat = "identity", fill = "blue") +
  coord_flip() +
  ggtitle("Top 10 Most Comment Channel") +
  ylab("Comments") +
  xlab("Channel")


```






